name: test
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install --frozen-lockfile
    - run: yarn test
